platform :ios, '8.0'
target "LoveHomeMerchant" do

pod 'IQKeyboardManager', '3.3.5'
pod 'Masonry', '0.6.4'
pod 'SVProgressHUD', '1.1.3'
pod 'AFNetworking', '2.6.3'
pod 'SDWebImage', '3.7.5'
pod 'MJExtension', '3.0.10'
pod 'MJRefresh', '3.1.0'
pod 'pop', '1.0.8'
pod 'VBFPopFlatButton', '0.0.6'
pod 'NJKWebViewProgress', '0.2.3'
pod 'ReactiveCocoa', '2.5'
pod 'JSPatch', '0.1.5'
pod 'Bugtags', '1.2.0'
pod 'Reachability', '3.2'
pod 'WebViewJavascriptBridge', '5.0.5'
pod 'DZNEmptyDataSet', '1.7.3'

end

